FROM alpine:3.9.4
RUN apk add --update ca-certificates \
 && apk add --update -t deps curl jq iproute2 bash \
 && apk del --purge deps \
 && rm /var/cache/apk/*

WORKDIR /
COPY bin/kube-controller-manager /usr/bin/kube-controller-manager
ENTRYPOINT ["/usr/bin/kube-controller-manager"]
